# Generated by Django 5.0.1 on 2024-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.URLField(default='https://media.publit.io/file/echocp/defaultcover.jpg', max_length=500),
        ),
    ]
