# Generated by Django 5.0.1 on 2024-01-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Text', 'Text')], default='Text', max_length=20),
        ),
    ]
