# Generated by Django 5.0.1 on 2024-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
