# Generated by Django 5.0.1 on 2024-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(default='https://media.publit.io/file/echopp/5856.jpg', max_length=500),
        ),
    ]
