# Generated by Django 5.0.1 on 2024-02-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_userprofile_city_alter_userprofile_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField(max_length=200)),
                ('website', models.URLField(max_length=100)),
                ('company', models.TextField(max_length=200)),
            ],
        ),
    ]
