# Generated by Django 5.0.1 on 2024-02-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sublike_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomments',
            name='comment_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_commentcomments', to='core.comment'),
        ),
    ]
